### PR TITLE
Update plugin-settings.md

### PR DESCRIPTION
**Pull request by firemankurt**
Added Predefined System Allocated Category Types

### CODE REVIEW

**Comment by firemankurt** [comment]
Took me a while to find these.  Thought it might help to put in docs

**Comment by daftspunk** [comment]
This might be too detailed, will save it for the API docs. Thanks though!

**Comment by LukeTowers** [comment]
@daftspunk Is there a repository for the API documentation? I'd like to add in the list of existing events but if it's going to get declined then I'd rather add it to the API docs repository instead

**Comment by daftspunk** [comment]
Not really, the API docs will be procedurally generated from the source code.

**Pull request closed without merging**
