### PR TITLE
Add documentation for accessing old value of model

### PR DESCRIPTION
**Pull request by meysammahfouzi**

### CODE REVIEW

**Comment by alxy** [comment]
I have to say I'm not sure if I like these addition to the docs (I have seen similar additions), as they are not specific to october and cover very special use cases. On the other side, they don't really harm anyone, so I think adding is alright. However, I prefer to have the docs as short and concise as possible.

**Comment by alxy** [comment]
@meysammahfouzi And regarding the technical site, did you check out these methods that already exist in Eloquent to see wether attributes have been modified: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L978

**Comment by LukeTowers** [comment]
@alxy I'm mostly of the same opinion, but I'd rather have more examples of cases where people have had to go elsewhere for the answers written into the docs first so that they don't end up posting on the github instead. We can always edit them down later. 

If you'd like to review them as they come in though that would be appreciated!

**Comment by meysammahfouzi** [comment]
@alxy I didn't know about that method, thanks! I think they are yet to be documented in Laravel docs.

**Pull request merged**
