### PR TITLE
refactor: Optimized the nginx server config block

### PR DESCRIPTION
**Pull request by mohsin**
Grouped patterns using regex to achieve the same result with half the lines

### CODE REVIEW

**Comment by daftspunk** [comment]
@mohsin 

Did you mean to close this?

**Comment by mohsin** [comment]
Oh no… It auto closed when I removed the fork. This is some nginx optimization to save some lines of code. Tested it out on my nginx server and works fine.

**Comment by daftspunk** [comment]
Ok, no worries, I think I can salvage it.

Can you confirm that dotfiles (`.env`) are protected with this configuration? We had some trouble with it in the past...

**Comment by mohsin** [comment]
Nope. Did not face any issues with dot files nor do these changes involve them.

**Comment by daftspunk** [comment]
Great, I can see this part has been untouched. Thanks!

**Comment by daftspunk** [comment]
Added this in 0bfde51e5f2a4affc26c64f0061f0497224ab49c

**Pull request closed without merging**
