### PR TITLE
Added introduction to Validation docs

### PR DESCRIPTION
**Pull request by jakxnz**

### CODE REVIEW

**Comment by LukeTowers** [comment]
Hmm, not sure this adds anything meaningfully different to the docs, weren't you going to add something explaining the use of model events and ApplicationExceptions for more complex business rule validation approaches?

**Comment by jakxnz** [comment]
Yeah, I wondered that while I was deciding what could be added. I ended up deciding that if the notion "Validation" has already been established surrounding the concepts of the Validator class then throwing an arbitrary exception doesn't fit that same definition (of "Validation").

My use case (prompting to this change) had an intention of learning and following the Validation pattern, and what I was missing was a clear context, differentiating stand-alone use of the Validation pattern and the decorated approach that the Validation trait provides. Not just a mention that they're different, but a clear context a) to establish the information and b) for the avoidance of doubt. So that's what this is hoping to add.

**Comment by daftspunk** [comment]
I tend to agree this adds more content without carrying much additional info

**Comment by jakxnz** [comment]
Closing this doesn't address the issue that there's room for ambiguity in the current docs. Is it not better to remove doubt than leave room for confusion?

**Comment by daftspunk** [comment]
This proposal doesn't quite clear up the ambiguity. I rewrote the paragraph to make it clearer

---

> **Note**: When working with models, October CMS ships with a useful [Validation Trait](../database/traits#validation) that implements the `Validator` class and supports the same rule definitions.

---

In other words, the Validation trait is an implementation of the Validator class

Is there anything else we can add to this, thoughts?

**Comment by jakxnz** [comment]
@daftspunk I'm not sure the issue is with the note. I found it very easy to overlook the note when reading for context in the article itself. I read a huge amount of the document, before I read the note, because the document doesn't explicitly explain what it's about to cover and I happily believed I was in the right place, when I really wasn't. This is why I've added that clarification to the scope of the document introduction itself, and not just the note.

**Pull request closed without merging**
