### PR TITLE
Added "Registring middleware" section

### PR DESCRIPTION
**Pull request by tobias-kuendig**

### CODE REVIEW

**Comment by daftspunk** [comment]
Thanks, it is also possible to register like this:

```
Cms\Classes\CmsController::extend(function($controller) {
    $controller->middleware('your middleware here');
});
```

**Comment by LukeTowers** [comment]
@tobias-kuendig Are you willing to add in the extra information for extending controllers to register middleware or would you like me to do it?

**Comment by tobias-kuendig** [comment]
Please, feel free to add it.

**Comment by LukeTowers** [comment]
Merged in #217

**Pull request merged**
