### PR TITLE
Added fifth method to define dropdown options

### PR DESCRIPTION
**Pull request by SaifurRahmanMohsin**
Provided documentation for an advanced method of defining options for form
dropdowns where the options are defined in a static method in a class different
to the model class associated with the form.

### CODE REVIEW

**Comment by SaifurRahmanMohsin** [comment]
@LukeTowers You may review this using [this plugin](https://github.com/SaifurRahmanMohsin/oc-selectable-plugin). Take a look at the Method 5 controller which demonstrates this.

**Comment by SaifurRahmanMohsin** [comment]
@bennothommo Could you verify this PR and if all is well merge it?

**Comment by LukeTowers** [comment]
@bennothommo how does this tie in with @jaxwilko's PR to add the `\Path\To\Class::method` option to the field parser?

**Comment by SaifurRahmanMohsin** [comment]
@LukeTowers This is a docs commit...

**Comment by bennothommo** [comment]
@LukeTowers I suppose that's a 6th option? :P

**Comment by SaifurRahmanMohsin** [comment]
Superseded by #478

**Pull request closed without merging**
