### PR TITLE
Remove outdated whereLoose and add new whereStrict

### PR DESCRIPTION
**Pull request by Samuell1**
Updated to match with Laravel 5.5 docs

### CODE REVIEW

**Comment by LukeTowers** [comment]
@Samuell1 could you link to where the change was made in Laravel? I don't remember reading about that.

**Comment by Samuell1** [comment]
@LukeTowers https://laravel.com/docs/5.5/collections#method-wherestrict

**Comment by LukeTowers** [comment]
@Samuell1 I mean when was whereLoose() removed?

**Comment by Samuell1** [comment]
@LukeTowers they changed it in 5.4 or 5.5 i think

**Comment by LukeTowers** [comment]
@Samuell1 thanks for looking into that for me!

**Pull request merged**
