### PR TITLE
Add missing slashes to sample configuration for nginx

### PR DESCRIPTION
**Pull request by pikanji**
Fix of the regular expression of rewrite paths for nginx configuration.
The root slash for each `rewrite` setting was missing in the regex.

Also added `rewrite` setteings for `/modules`, `/plugins`, and `/tests`.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@pikanji what issue does this solve exactly?

**Comment by pikanji** [comment]
@LukeTowers I assumed that these lines I modified were sample configurations to disallow public access to the files in the specified directories at the project root. For example, I assumed this line `rewrite ^bootstrap/.* /index.php break;` is to hide all the files and directories in the `bootstrap` directory at the root of the project. However, with this line in the nginx configuration, the visitors to the site still able to access these files. By adding slash in the regex, it successfully disallows public access to these files. The same applies to all other lines I modified.
Also, I added similar configuration to hide `/modules`, `/plugins`, and `/tests` directories, since these directories are also those we don't want visitors to access directly.

**Comment by LukeTowers** [comment]
Could you switch it to a whitelist approach instead of a blacklist approach following https://github.com/octobercms/october/blob/master/modules/system/console/OctoberMirror.php#L33-L72 as a guide? Also whatever final solution we come up with needs to support both being installed in domain root and in a subfolder

**Comment by pikanji** [comment]
@LukeTowers Thanks for the whitelist. I have created another PR (#276) for the whitelist strategy.

**Pull request closed without merging**
