### PR TITLE
Allow access to check Let's Encrypt

### PR DESCRIPTION
**Pull request by EbashuOnHolidays**

### CODE REVIEW

**Comment by LukeTowers** [comment]
Won't this prevent Nginx from passing the request to October if it fails?

**Comment by mahony0** [comment]
Actually, a more robust protection for dot (hidden) files rule would be logical to apply for nginx servers. For example:

```nginx
# block access to all dot files and folders except .well-known
location ~ /\.(?!well-known).* { deny all; }
```

This rule will allow access to files inside .well-known but restrict access to all other dot files like .htaccess, .env or .git etc.

**Comment by bennothommo** [comment]
@mahony0 I like that suggestion a lot better. Would you mind submitting a PR with that change instead? I'll close this one as it looks to be abandoned.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Pull request closed without merging**
