### PR TITLE
form_config <> config_form inversion

### PR DESCRIPTION
**Pull request by RomainMazB**
To match the CLI controller generation

### CODE REVIEW

**Comment by bennothommo** [comment]
@RomainMazB Thanks for your contribution, but there's no real reason to change this. Both strings will work.

**Comment by LukeTowers** [comment]
@bennothommo what do you mean both will work? Doesn't it depend on what the file is named?

**Comment by bennothommo** [comment]
@LukeTowers I mean both will work in the context of documentation.

**Comment by LukeTowers** [comment]
@bennothommo while technically true it might be better to have the docs match what the scaffolding command and builder plugin generate.

**Comment by bennothommo** [comment]
@LukeTowers that's fair.

@RomainMazB sorry for the premature closing of the PR. :)

**Comment by RomainMazB** [comment]
@bennothommo No problem: your point was not bad: anything the config name's file is, it will work.

I just felt like Luke : if it could be anything, I don't see any reason to not sync it with the scaffolding command to add (a very little) more consistency.

**Pull request merged**
