### PR TITLE
Add logical operators and custom vars for filters information

### PR DESCRIPTION
**Pull request by ayumi-cloud**
This pr adds some extra information to let users know what logical operators and custom variables users can use for the filters in the list widget.

As per github issue found here: https://github.com/octobercms/docs/issues/426

p.s. Code line 520 says: `??? | <>`

As I don't know what `<>` exactly means, so let me know and I will add the correct label next to it.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@ayumi-cloud I'm pretty sure that's just a SQL not equal to. TBH I'm not sure why we need a section like that for those operators since whatever operators are available is defined by the selected DB driver.

**Comment by ayumi-cloud** [comment]
@LukeTowers 

I will explain our reasons why we wanted to create this pr.

1. We were searching on other websites for a list of available `yaml`  logical operators. This wasted time, when we could have just found them on the octobercms website instead.

2. If you do a search on the doc's web page you won't find tings like `afterDate` being mentioned at all.

3. Table of Contents there was an error and missing `- [Filter Dependencies](#filter-scope-options)`

image

Links:

- https://octobercms.com/docs/backend/lists

- https://github.com/octobercms/october/blob/master/modules/backend/widgets/Filter.php

**Comment by LukeTowers** [comment]
> We were searching on other websites for a list of available yaml logical operators. This wasted time, when we could have just found them on the octobercms website instead.

@ayumi-cloud the problem with that though is that these options are not YAML logical operators. The value is inserted right into the SQL used to do the filtering.

**Comment by ayumi-cloud** [comment]
@LukeTowers Sorry late reply, just going through all my open pr's and issues to see if I missed anything.

If this pr is no good to be added to the doc's please feel free to close this pr, thanks.

**Comment by LukeTowers** [comment]
@ayumi-cloud can you resubmit this without the logical operators and fixing the link to the dependencies section?

**Pull request closed without merging**
