### PR TITLE
Document model adders

### PR DESCRIPTION
**Pull request by scottbedard**
Related to https://github.com/octobercms/october/issues/3407 and https://github.com/octobercms/library/pull/306

### CODE REVIEW

**Comment by LukeTowers** [comment]
Could you add docs for the other helpers?

**Comment by LukeTowers** [comment]
Try listening to `oc.updateUi` on the window: https://github.com/octobercms/october/blob/master/modules/system/assets/ui/js/tab.js#L59

**Comment by scottbedard** [comment]
@LukeTowers Hows this? I didn't really know how to document the params without having it look silly, so I added examples of the other helpers to the code block.

**Comment by LukeTowers** [comment]
Perfect @scottbedard; thanks!

**Pull request merged**
