### PR TITLE
Add a warning message for FLUSHDB command

### PR DESCRIPTION
**Pull request by fansaien**
I found my Redis database has been deleted. We should set a specific database for the Cache when using Redis.

### CODE REVIEW

**Comment by LukeTowers** [comment]
Please provide more details with what you mean by that.

**Comment by fansaien** [comment]
Set the Cache in .env
```ini
CACHE_DRIVER=redis
```


With `php artisan october:up` command

The Redis Logs:

```bash
"GET" "october:system_parameters-system-update-count"
"SETEX" "october:system_parameters-system-update-count" "300" "a:1:{i:0;O:8:\"stdClass\":5:{s:2:\"id\";i:1;s:9:\"namespace\";s:6:\"system\";s:5:\"group\";s:6:\"update\";s:4:\"item\";s:5:\"count\";s:5:\"value\";s:1:\"0\";}}"
"DEL" "october:system_parameters-system-update-count"
"FLUSHDB"
```

This command `php artisan october:up` will flush the Redis database.

**Comment by LukeTowers** [comment]
What is your proposed solution? AFAIK redis as a cache driver isn't a permanent data store, it's a temporary caching layer.

**Comment by fansaien** [comment]
Right now, my solution is setting a database for cache, for example database=1 for Cache, database=2 for Queue, database=3 for Sessions. 

Moreover, I do not think it should run this command to flush the DB. Cache Manager can delete the keys which created by itself but not all the others.

The default database is 0. If the Cahce, Queue and Sessions all set to Redis, that means the Cache can delete all.

**Comment by LukeTowers** [comment]
Ah, so then the problem is that the cachehelper clears the entire redis datastore, even if it's being used for other purposes too?

**Comment by LukeTowers** [comment]
@bennothommo do you have any thoughts on this?

**Comment by bennothommo** [comment]
@fansaien the `FLUSHDB` command should only be flushing the current database (in the case of the CacheHelper, it should be only erasing the Redis connection and database defined for `stores.redis.connection` in `config/cache.php`). The `FLUSHALL` command would be the command that flushes every database.

**Comment by bennothommo** [comment]
I've just tested this out on my own October CMS install (which is running the L6 upgrade), setting the cache to database 0 and sessions to database 1, and ran `php artisan october:up`. The cache database was cleared, but the sessions was not. It may be possible that something has been fixed in Laravel 6, or there is something else at play.

**Comment by LukeTowers** [comment]
@bennothommo I believe the issue is that the same Redis connection is being used for cache & sessions & queues. We should probably add the warning about not sharing the cache database with any other databases to the config files.

**Comment by fansaien** [comment]
@LukeTowers @bennothommo 

Sorry for misleading here. I know the `FLUSHDB` only flush the current selected database not all, but it is still very dangerous. So, I want other developers know that.

There are three types of data in the Cache database:

1. System cached data. For example:  `october:system:**`, `october:backend::*` and maybe `october:combiner*` (I do not know that key)
2. Developers cached data by `Cache::remember($redisKey, time)`
3. All the other data

I would recommend only deleting the the system cached data with `php artisan october:up `

For example, one developer using `Cache::remember(key, 'Two days')` or `Cache::rememberForever(key)` to save data in Cache database. However, it can be removed when updating some plugins.

**Comment by LukeTowers** [comment]
@fansaien I would say that's a non-issue. The cache is a volatile data store meant to be used only for performance reasons. Your code should not care that rememberForever isn't actually remembering something forever, nor should it care that a cache item expired before it was told do because the cache was cleared manually.

I'm not sure why this is a problem for you? Could you provide more information on why it's an issue?

**Comment by bennothommo** [comment]
@LukeTowers @fansaien I get your points, but this same thing would occur in numerous other scenarios, like:

- Using the same directory for cache, queues and sessions with the `file` driver
- Using the `cache:clear` Artisan command
- Using the same instance of `memcache`

I would suggest a more generic tip suggesting that you shouldn't use the exact same storage for cache, sessions and the queue would suffice, otherwise clearing the cache may invalidate sessions or remove the queued jobs.

**Comment by fansaien** [comment]
@LukeTowers 

My big issue was setting the default 0 to the Cache and I saved other important data in that database too. After one day, I found that database was empty.

For the `Cache::remember`, I agree with you that cache used for the performance. However, I do not think other program can delete my cached data.

For example, I run a long-time task at mid-night and save the results into cache db. Absolutely, I do not want this task can be running on the daytime.

**Comment by LukeTowers** [comment]
@fansaien fair enough re: wanting to cache the results of intensive work during off hours, but if it's essential for it to not be run during working hours then you have to use a more persistent form of caching. The Cache system is inherently volatile. There are a number of ways for it to be cleared, and you should never rely on keys to be present for any other reason than to improve performance.

**Comment by daftspunk** [comment]
Thanks for pointing this out @fansaien. Will ensure this no longer happens in the next release, as opposed to documenting this.

**Pull request closed without merging**
