### PR TITLE
Updated $elevated param to be able to listen backend events

### PR DESCRIPTION
**Pull request by arzola**
Since it's hard to find this to new users

### CODE REVIEW

**Comment by arzola** [comment]
Thanks, I will specify which events require it

**Comment by arzola** [comment]
Updated

**Comment by LukeTowers** [comment]
Please list the exact events disabled. `backend.form.extendFields` for instance is run on a `/backend/**` path, but it usable without `$elevated = true`.

**Comment by arzola** [comment]
Ok Luke :) 🎯 i will do that too, but actually `backend.form.extendFields` works to extend the form behaviour because usually is called in *another* path something like `vendornamespace/plugin/controller/action` and not on the `backend/backend/*` path.

i refer to the backend path (the backend controller) not the cms.BackendUri

**Comment by LukeTowers** [comment]
These lines https://github.com/octobercms/october/blob/master/modules/system/ServiceProvider.php#L117-L143 are what actually govern the use of the `$elevated = true;` property, I'll add something to the plugin documentation instead

**Comment by daftspunk** [comment]
This documents a fix for a symptom of a configuration issue. The elevated process is designed to protect plugins from locking a user out of their site, see the code here: https://github.com/octobercms/october/blob/master/modules/system/ServiceProvider.php#L117-L143

This logic should probably be documented fully and included as part of the **plugin-registration.md** file.

**Comment by LukeTowers** [comment]
Added in https://github.com/octobercms/docs/commit/3cb59ff628ace8fa8c8351cbd230c5410a6700b6

**Pull request closed without merging**
